### ISSUE TITLE
node >= 0.12

### ISSUE THREAD

**Issue by orlin** [gromnitsky/coffee-inline-map#1]
I noticed the `node-0.12` branch.  Is it ready for release?  I'd like to use this soon...  I'm actually on `iojs` which I'm guessing will work too.

Also noticed that you are dropping support for `0.10`...  Do you have to?  It's no big deal, as I mostly just test against `0.10` anyway.

Looks like a useful project.

**Comment by gromnitsky** [comment]
use the master branch, it works w/ iojs & node 0.10x & supports the latest version of coffeescript.

any other branches are for testing only => ignore them.
