### ISSUE TITLE
Support for --nodejs option

### ISSUE THREAD

**Issue by XVincentX** [gromnitsky/coffee-inline-map#4]
It would be great if this tool would be able to forward `--nodejs` options to the underlying `coffee` executable!

**Comment by gromnitsky** [comment]
coffee-inline-map is not an interpreter & is _not_ a wrapper around coffee executable. it's a usual node program that uses js libs from the coffeescript npm package.

you can always run it like

```
$ node --node-opt1 --node-opt2 -- `which coffee-inline-map` file.coffee
```
